config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items
    resources :genres, only: [:create, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: "homes#top"
    get 'homes/about'
    resource :customers, only: [:show, :edit, :update]
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/destroy_all' => 'cart_items#destroy_all'
      end
    end
    get 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]  do
      collection do
        post :confirm
      end
    end
    resources :deliveries, only: [:create, :index, :edit, :destroy, :update]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  has_one_attached :image

  validates :customer_id, :item_id, :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :phone_number, :address, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer


  with_options presence: true do
    validates :post_code
    validates :address
    validates :address_name
    validates :customer_id
  end

  def delivery_display
    '〒' + post_code + ' ' + address + ' ' + address_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  validates :price, presence: true

  has_one_attached :image


  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_type: { credit_card: 0, transfer: 1 }
  enum order_status: { machi: 0, kakuninn: 1, seisaku: 2, junbi: 3, hasso: 4 }

  belongs_to :customer
  has_many :order_details

  # 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum create_status: { huka: 0, machi: 1, seisaku: 2, kanryo: 3 }

  belongs_to :order
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:update] = 'You have updated customer successfully.'
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :address, :is_deleted)
  end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!, only: [:edit, :update]
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
     redirect_to admin_genres_path, notice: "ジャンル名を登録しました"
    else
      @genres = Genre.all
      render :index
    end

  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンル名を編集しました"
    else
      render :edit
    end
  end

  private

  # def set_genre
  #   @genre = Genre.find(params[:id])
  # end

  def genre_params
    params.require(:genre).permit(:item_id, :name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :update]
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_items_path, notice: "商品を登録しました"
    else
      @items = Item.all
      render :new
    end
  end

  def index
    @items = Item.all

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item.id), notice: "商品を変更しました"
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])

    if params[:order][:order_status] == "kakuninn"
      @order.update(order_params)
      @order_details = @order.order_details
      @order_details.update(create_status: 1)
    end
    if @order.update(order_params)
      redirect_to admin_order_path(@order)
    else
      render :show
    end
  end

private

    def order_params
      params.require(:order).permit(:pay_type, :delivery_post_code, :delivery_address, :delivery_name, :bill, :postage, :order_status )
    end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>
        <div>会員ID</div><div><%= @customer.id %></div>
        <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
          <div class="form-group mr-3">氏名<%= f.text_field :last_name %> <%= f.text_field :first_name %></div>
          <div class="form-group mr-3">フリガナ<%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></div>
          <div class="form-group mr-3">住所<%= f.text_field :address %></div>
          <div class="form-group mr-3">電話番号<%= f.text_field :phone_number %></div>
          <div class="form-group mr-3">メールアドレス<%= f.text_field :email %></div>
          <div class="form-group mr-3">会員ステータス<%= f.radio_button :is_deleted, "false" %><%= f.label :is_deleted, "有効" %><%= f.radio_button :is_deleted, "true" %><%= f.label :is_deleted, "退会" %></div>
          <div class="form-group mr-3"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/customers/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col">
        <table class="table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to admin_customer_path(customer.id) do %>
                    <%= customer.last_name %><%= customer.first_name %>
                  <% end %>
              </td>
              <td><%= customer.email %></td>
              <td><%= customer.is_deleted %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/admin/customers/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col">
        <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h3>
        <div>
          <p>会員ID</p>
          <%= @customer.id %>
        </div>
        <div>
          <p>氏名</p>
          <%= @customer.last_name %><%= @customer.first_name %>
        </div>
        <div>
          <p>フリガナ</p>
          <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
        </div>
        <div>
          <p>郵便番号</p>
          <%= @customer.post_code %>
        </div>
        <div>
          <p>住所</p>
          <%= @customer.address %>
        </div>
        <div>
          <p>電話番号</p>
          <%= @customer.phone_number %>
        </div>
        <div>
          <p>メールアドレス</p>
          <%= @customer.email %>
        </div>
        <div>
          <p>会員ステータス</p>
          <%= @customer.is_deleted ? "退会" :  "有効" %>
        </div>
        <div><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></div>
        <div><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %></div>
      </div>
    </div>
  </div>
</main>