config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items
    resources :genres, only: [:create, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: "homes#top"
    get 'homes/about'
    resource :customers, only: [:show, :edit, :update]
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/destroy_all' => 'cart_items#destroy_all'
      end
    end
    get 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]  do
      collection do
        post :confirm
      end
    end
    resources :deliveries, only: [:create, :index, :edit, :destroy, :update]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  has_one_attached :image

  validates :customer_id, :item_id, :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :phone_number, :address, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer


  with_options presence: true do
    validates :post_code
    validates :address
    validates :address_name
    validates :customer_id
  end

  def delivery_display
    '〒' + post_code + ' ' + address + ' ' + address_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  validates :price, presence: true

  has_one_attached :image


  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_type: { credit_card: 0, transfer: 1 }
  enum order_status: { machi: 0, kakuninn: 1, seisaku: 2, junbi: 3, hasso: 4 }

  belongs_to :customer
  has_many :order_details

  # 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum create_status: { huka: 0, machi: 1, seisaku: 2, kanryo: 3 }

  belongs_to :order
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!, only: [:edit, :update]
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
     redirect_to admin_genres_path, notice: "ジャンル名を登録しました"
    else
      @genres = Genre.all
      render :index
    end

  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンル名を編集しました"
    else
      render :edit
    end
  end

  private

  # def set_genre
  #   @genre = Genre.find(params[:id])
  # end

  def genre_params
    params.require(:genre).permit(:item_id, :name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :update]
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_items_path, notice: "商品を登録しました"
    else
      @items = Item.all
      render :new
    end
  end

  def index
    @items = Item.all

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item.id), notice: "商品を変更しました"
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])

    if params[:order][:order_status] == "kakuninn"
      @order.update(order_params)
      @order_details = @order.order_details
      @order_details.update(create_status: 1)
    end
    if @order.update(order_params)
      redirect_to admin_order_path(@order)
    else
      render :show
    end
  end

private

    def order_params
      params.require(:order).permit(:pay_type, :delivery_post_code, :delivery_address, :delivery_name, :bill, :postage, :order_status )
    end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/_errors.html.erb
<% if genre.errors.any? %>
  <div id="error_explanation">
    <h3><%= genre.errors.count %> 件のエラーが発生しました</h3>
    <ul>
      <% genre.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/genres/edit.html.erb
<div class="container">
 <h2>ジャンル編集</h2>
  <div class="row">
    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
    <%= render 'admin/genres/errors', genre: @genre %>
      <div class="form-group">
        <label for="genre_name">ジャンル名</label>
        <%= f.text_field :name, autofocus: true, id: "genre_name", placeholder: "ジャンル名", class: "form-control name" %>
      </div>
      <div class="form-inline">
        <%= f.submit "変更を保存する", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <h1>ジャンル一覧・追加</h1>
 <div class="row">
  <div class="col-md-8 offset-md-1">
    <%= form_with model: @genre, url: admin_genres_path,  method: :post do |f| %>
    <%= render 'admin/genres/errors', genre: @genre %>
      <div class="form-group">
        <label for="genre_name">ジャンル名</label>
        <%= f.text_field :name, autofocus: true, id: "genre_name", placeholder: "ジャンル名", class: "form-control name" %>
      </div>
      <div class="form-inline mr-2">
        <%= f.submit "新規登録", class: 'btn btn-success' %>
      </div>
    <% end %>
    <% @genres.each do |genre| %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>ジャンル</tr>
          <tr colspan="2"></tr>
        </thead>
        <tbody>
          <td>
            <%= genre.name %>
          </td>
          <td>
            <%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-success' %>
          </td>
        </tbody>
      </table>
    <% end %>
  </div>
 </div>
</div>

app/views/admin/items/_errors.html.erb
<% if item.errors.any? %>
  <div id="error_explanation">
    <h3><%= item.errors.count %> 件のエラーが発生しました</h3>
    <ul>
      <% item.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<div class="container">
      <h1>商品編集</h1>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
       <%= render 'admin/items/errors', item: @item %>
      <div class="form-group">
       <label for="item_image">商品画像</label>
       <%= f.file_field :image, placeholder: "商品画像", class: "form-control-file item_image", accept: "image/*" %>
      </div>
       <div class="form-group">
         <label for="item_name">商品名</label>
         <%= f.text_field :name, autofocus: true, id: "item_name", placeholder: "名前", class: "form-control name" %>
       </div>
       <div class="form-group">
         <label for="item_introduction">商品説明</label>
         <%= f.text_area :introduction, placeholder: "商品説明", class: "form-control introduction" %>
       </div>
       <div class="form-group">
         <label for="item_genre">ジャンル</label>
         <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
       </div>
       <div class="form-group">
         <label for="item_price">税抜価格</label>
         <%= f.number_field :price, placeholder: "1000", class:"form-control price" %>円
       </div>
       <div class="form-group">
         <label for="item_is_active">販売ステータス</label>
         <%= f.radio_button :is_active, "true" %>
         <%= f.label :is_active, "販売中" %>
         <%= f.radio_button :is_active, "false" %>
         <%= f.label :is_active, "販売停止中" %>
       </div>
       <div class="form-group">
         <%= f.submit '変更を保存する', class: 'btn btn-success' %>
       </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>

<div class="col-md-8 offset-md-1">
  <table class="table table-hover table-inverse">

    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
        <th colspan="5"></th>
      </tr>
    </thead>
    <tbody>
     <% @items.each do |item| %>
        <tr>
          <td><%= item.id  %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active %>
             <%= link_to "販売中", admin_items_path(item.id, post: {is_actived: true}), method: :put, class: 'btn btn-success' %>
            <% else %>
             <%= link_to "販売停止中", admin_items_path(item.id, post: {is_actived: false}), method: :put, class: 'btn btn-outline-secondary ' %>
            <% end %>
          </td>
        </tr>
     <% end %>
    </tbody>
  </table>
  <div>
    <%= link_to "新規登録", new_admin_item_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">>
      <div class="form-group">
        <h1>商品新規登録</h1>
      <%= form_with model: @item, url: admin_items_path(@item.id), method: :post do |f| %>
      <%= render 'admin/items/errors', item: @item %>
      <div class="form-group">
       <label for="item_image">商品画像</label>
       <%= f.file_field :image, placeholder: "商品画像", class: 'form-control-file item_image', accept: "image/*" %>
      </div>
       <div class="form-group">
         <label for="item_name">商品名</label>
         <%= f.text_field :name, autofocus: true, id: "item_name", placeholder: "名前", class: 'form-control name' %>
       </div>
       <div class="form-group">
         <label for="item_introduction">商品説明</label>
         <%= f.text_area :introduction, placeholder: "商品説明", class: 'form-control introduction' %>
       </div>
       <div class="form-group">
         <label for="item_genre">ジャンル</label>
         <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
       </div>
       <div class="form-group">
         <label for="item_price">税抜価格</label>
         <%= f.number_field :price, placeholder: "1000", class: 'form-control price' %>円
       </div>
       <div class="form-group">
         <label for="item_is_active">販売ステータス</label>
          <%= f.radio_button :is_active, "true" %>
          <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active, "false" %>
          <%= f.label :is_active, "販売停止中" %>
       </div>
       <div class="form-group">
         <%= f.submit '新規登録', class: 'btn btn-success' %>
       </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
 <h2>商品詳細</h2>
 <div class="container">
  <div class="row">
    <div>
      <div class="col-4">
      <p><%= image_tag @item.image, size:"500x500" %></p>
      </div>
    </div>
     <div class="col-md-4">
      <div class="form-group">
      <p>商品名 <%= @item.name %></p>
      </div>
      <div class="form-group">
      <p>商品説明文 <%= @item.introduction %></p>
      </div>
      <div class="form-group">
      <p>ジャンル <%= @item.genre.name %></p>
      </div>
      <div class="form-group">
      <p>税込価格(税抜価格) <%= @item.with_tax_price.to_s(:delmited) %>(<%= @item.price %>)円</p>
      </div>
      <div class="form-group">
      <p>
        販売ステータス
        <% if @item.is_active %>
         <%= link_to "販売中", admin_item_path(@item.id, post: {is_actived: true}), method: :put %>
        <% else %>
         <%= link_to "販売停止中", admin_item_path(@item.id, post: {is_actived: false}), method: :put %>
        <% end %>
      </p>
      </div>
      <div class="form-group">
        <%= link_to '編集する', edit_admin_item_path(@item.id), class: 'btn btn-success' %>
      </div>
     </div>
  </div>
 </div>

app/views/admin/orders/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-10">
        <h3>注文履歴詳細</h3>
        <table class="table">
          <tbody>
            <tr>
              <th>購入者</th><th><%= @customer.first_name %><%= @customer.last_name %></th>
            </tr>
            <tr>
              <th>注文日</th><th><%= @order.created_at %></th>
            </tr>
            <tr>
              <th>配送先</th>
              <th>
                <%= @order.delivery_post_code %><%= @order.delivery_address %><br />
                <%= @order.delivery_name %><br />
              </th>
            </tr>
            <tr>
              <th>支払方法</th><th><%= @order.pay_type_i18n %></th>
            </tr>
            <tr>
              <th>注文ステータス</th>
              <th>
                <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
                  <%= f.select :order_status, Order.order_statuses_i18n.invert %>
                  <%= f.submit "更新" , class:"btn btn-sm btn-success"%>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-8">
        <table class="table">
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @order_details.each do |order_detail| %>
            <tr>
              <td>
                <%= order_detail.item.name %>
              </td>
              <td>
                <%= order_detail.item.price %>
              </td>
              <td>
                <%= order_detail.amount %>
              </td>
              <td><%= order_detail.subtotal %></td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                <div>
                  <td>
                    <%= f.select :create_status, OrderDetail.create_statuses_i18n.invert %>
                  </td>
                  <td><%= f.submit "更新" , class:"btn btn-sm btn-success"%></td>

                </div>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-4">
        <h3>商品合計</h3><div><%= @order.bill - 800 %>円</div>
        <h3>送料</h3><div><%= @order.postage %>円</div>
        <h3>請求金額</h3><div><%= @order.bill %>円</div>
      </div>
    </div>
  </div>
</main>