config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items
    resources :genres, only: [:create, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: "homes#top"
    get 'homes/about'
    resource :customers, only: [:show, :edit, :update]
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/destroy_all' => 'cart_items#destroy_all'
      end
    end
    get 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]  do
      collection do
        post :confirm
      end
    end
    resources :deliveries, only: [:create, :index, :edit, :destroy, :update]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  has_one_attached :image

  validates :customer_id, :item_id, :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :phone_number, :address, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer


  with_options presence: true do
    validates :post_code
    validates :address
    validates :address_name
    validates :customer_id
  end

  def delivery_display
    '〒' + post_code + ' ' + address + ' ' + address_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  validates :price, presence: true

  has_one_attached :image


  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_type: { credit_card: 0, transfer: 1 }
  enum order_status: { machi: 0, kakuninn: 1, seisaku: 2, junbi: 3, hasso: 4 }

  belongs_to :customer
  has_many :order_details

  # 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum create_status: { huka: 0, machi: 1, seisaku: 2, kanryo: 3 }

  belongs_to :order
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!, only: [:edit, :update]
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
     redirect_to admin_genres_path, notice: "ジャンル名を登録しました"
    else
      @genres = Genre.all
      render :index
    end

  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンル名を編集しました"
    else
      render :edit
    end
  end

  private

  # def set_genre
  #   @genre = Genre.find(params[:id])
  # end

  def genre_params
    params.require(:genre).permit(:item_id, :name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :update]
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_items_path, notice: "商品を登録しました"
    else
      @items = Item.all
      render :new
    end
  end

  def index
    @items = Item.all

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item.id), notice: "商品を変更しました"
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mb-0">
    <div class="small text-center text-muted" style="margin: 50px 0;">Copyright © 2022  SHM_GAMING</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/"><span>ながのCAKE</span></a>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
               <li class = "nav-item mr-3">
                <%= link_to(admin_items_path, class:"btn btn-sm btn-outline-secondary") do %>
                  商品一覧
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(admin_customers_path, class:"btn btn-sm btn-outline-secondary") do %>
                  会員一覧
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(root_path, class:"btn btn-sm btn-outline-secondary") do %>
                  注文履歴一覧
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(admin_genres_path, class:"btn btn-sm btn-outline-secondary") do %>
                  ジャンル一覧
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(destroy_admin_session_path, method: :delete, class:"btn btn-sm btn-outline-secondary") do %>
                  ログアウト
                <% end %>
               </li>
              <% elsif customer_signed_in? %>
               <li class="mx-auto"><p class="logincustomer nav-link text-dark">ようこそ<%= current_customer.first_name + current_customer.last_name %>さん！</p></li>
               <li class = "nav-item mr-3">
                <%= link_to(customers_path, class:"btn btn-sm btn-outline-secondary") do %>
                  マイページ
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(items_path, class:"btn btn-sm btn-outline-secondary") do %>
                  商品一覧
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(cart_items_path, class:"btn btn-sm btn-outline-secondary") do %>
                  カート
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(destroy_customer_session_path, method: :delete , class:"btn btn-sm btn-outline-secondary") do %>
                  ログアウト
                <% end %>
               </li>
              <% else %>
               <li class = "nav-item mr-3">
                <%= link_to(homes_about_path, class:"btn btn-sm btn-outline-secondary") do %>
                  About
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(items_path, class:"btn btn-sm btn-outline-secondary") do %>
                  商品一覧
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(new_customer_registration_path, class:"btn btn-sm btn-outline-secondary") do %>
                  新規登録
                <% end %>
               </li>
               <li class = "nav-item mr-3">
                <%= link_to(customer_session_path, class:"btn btn-sm btn-outline-secondary") do %>
                  ログイン
                <% end %>
               </li>
              <% end %>
            </ul>
          </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>NaganoCake</title>
  </head>

  <body>
    <% if flash[:notice] %>
     <div class="notification is-info">
      <p class="notice"><%= notice %></p>
     </div>
    <% end %>

    <% if flash[:alert] %>
     <div class="notification is-danger">
      <p class="alert"><%= alert %></p>
     </div>
    <% end %>

    <header>
     <%= render "layouts/header" %>
    </header>

    <main>
      <%= yield %>
    </main>

  </body>
</html>